version: '3.7'

services:
  postgres:
    image: postgres:latest
    container_name: bitbox-postgres
    environment:
      POSTGRES_DB: db_bitbox
      POSTGRES_USER: bitbox_user
      POSTGRES_PASSWORD: bitbox_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/db_bitbox.sql:/docker-entrypoint-initdb.d/db_bitbox.sql
    ports:
      - "5433:5433"
    networks:
      - bitbox-network

  teleport:
    build: ./teleport
    container_name: bitbox-teleport
    environment:
      TELEPORT_AUTH_TOKEN: your-teleport-auth-token
      TELEPORT_CLUSTER_NAME: bitbox-cluster
    ports:
      - "3025:3025"
      - "3080:3080"
      - "3024:3024"
      - "5433:5433"
    depends_on:
      - postgres
    networks:
      - bitbox-network

networks:
  bitbox-network:
    driver: bridge

volumes:
  postgres_data:
