version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: bitbox_postgres
    env_file:
      - .env
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - bitbox_network

volumes:
  postgres_data:

networks:
  bitbox_network:
